#! /bin/bash
docker run -d \
    --network todo-net --network-alias mysql \
    -v todo-mysql-data:/var/lib/mysql \
    -e MYSQL_ROOT_PASSWORD=secret \
    -e MYSQL_DATABASE=todos \
    arm64v8/mysql:latest \
    mysqld --default-authentication-plugin=mysql_native_password
